### ISSUE TITLE
may you share original data files as well

### ISSUE THREAD

**Issue by Sandy4321** [xswang/Field-aware-Factorization-Machines-Mpi#3]
there is only  ffm format data files, but on order to understand how it works may you share original data files as well and how you created this  ffm format data files

https://github.com/xswang/ffm_mpi/tree/master/data

**Comment by xswang** [comment]
OK. there are three columns of one feature. 
the first is feature group index, the second is the feature index, the third is always 1 which means this feature is used.
for example, if you have two feature: gender and country. gender has two vaule female and male, country has three value:  China, America, Russia.   and now ,for example you are male from America, the result of the instance feature is :   0:1:1 1:3:1.
because we use [0 1] indicate male,   [0 1 0] indicate America, and because the number of feature in gender is 2, and America is the 2nd in the country, so the America is the fourth feature in all, then it is 3:1, the country is the 2nd feature group, at last, the result is 1:3:1.
Any question, please feel free to let me know.

**Comment by xswang** [comment]
I recommand another project which also implement FM and FFM model: https://github.com/aksnzhy/xlearn

**Comment by xswang** [comment]
The origin data files format is like criteo:
https://www.kaggle.com/c/criteo-display-ad-challenge/data

2017-12-18 3:03 GMT+08:00 Sandy4321 <notifications@github.com>:

**Comment by xswang** [comment]
there are three columns of one feature.
the first is feature group index, the second is the feature index, the third is always 1 which means this feature is used.
for example, if you have two feature: gender and country. gender has two vaule female and male, country has three value: China, America, Russia. and now ,for example you are male from America, the result of the instance feature is : 0:1:1 1:3:1.
because we use [0 1] indicate male, [0 1 0] indicate America, and because the number of feature in gender is 2, and America is the 2nd in the country, so the America is the fourth feature in all, then it is 3:1, the country is the 2nd feature group, at last, the result is 1:3:1.

for example, male from America,
for the male, the result is 0:1:1,   the first number 0 (0:1:1) means male in the 1st feature group gender, the second number 1 (0:1:1) means male is the 2nd feature in the feature group.  all index start from 0.
for the America, the result is 1:3:1, the first number 1 (1:3:1) means  America in the 2nd feature group country, the second number 3 (1:3:1) means America is the 2nd feature in the feature group, and since feature numbers before it is 3 (two in the first feature group(female, male), 1 in the sencod group(China)), so the index of America is 2 + 2 - 1 = 3.

the original file as following:
gender   country 
male       America
the result will be: 
you first can transform it to : [0 1 0 1 0] , the red two number is the feature in the first feature group, the blue three number is the feature in the second feature group. so the result is 0:1:1, 1:3:1

another example, if we have another feature group career: student, teacher, engineer
the original file as following:
gender    country    career
female     Russia     teacher
first transform it to format[1 0 0 0 1 0 1 0], and the result is 0:0:1, 1:4:1, 2:6:1

**Comment by Sandy4321** [comment]
super
this one is good too
https://www.analyticsvidhya.com/blog/2018/01/factorization-machines/

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
